import { Component, OnInit, PLATFORM_ID, inject } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { AuthService } from '../../core/services/auth.service';


import { isPlatformBrowser } from '@angular/common';
@Component({
  selector: 'app-oauth-success',
  standalone: true,
  imports: [],
  template: `
    <div class="oauth-container">
      <div class="oauth-card">
        <div class="spinner"></div>

        <h2>Signing you in...</h2>
        <p>Please wait while we complete your Google sign-in.</p>
      </div>
    </div>
  `,
  styles: [`
    .oauth-container {
      display: flex;
      align-items: center;
      justify-content: center;
      min-height: 100vh;
    }

    .oauth-card {
      text-align: center;
    }

    .spinner {
      width: 48px;
      height: 48px;
      border: 4px solid #ddd;
      border-top-color: #2D8A6E;
      border-radius: 50%;
      margin: 0 auto 24px;
      animation: spin 0.8s linear infinite;
    }

    @keyframes spin {
      to {
        transform: rotate(360deg);
      }
    }
  `]
})
export class OauthSuccessComponent implements OnInit {

  private route = inject(ActivatedRoute);
  private router = inject(Router);
  private platformId = inject(PLATFORM_ID);
  private authService = inject(AuthService);

  ngOnInit(): void {
    if (!isPlatformBrowser(this.platformId)) {
      return;
    }
    this.route.queryParamMap.subscribe(params => {

      const token = params.get('token');

      console.log('OAuth token:', token);

      if (!token) {
        console.error('OAuth token missing in redirect');
        this.router.navigate(['/login']);
        return;
      }

      // Save REAL JWT generated by Spring Boot
      localStorage.setItem('token', token);
      this.authService.setSession(token, null, null, 'USER');
      // Remove ?token=... from address bar
      this.router.navigate(['/dashboard'], {
        replaceUrl: true
      });
    });
  }
}